# Generated by Django 3.2 on 2021-05-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlpquery', '0003_testquerydlp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testquerydlp',
        ),
    ]
